[workspace]
authors = ["ElouenCorvest <elouen2000@gmail.com>"]
channels = ["conda-forge"]
name = "mxl-bricks-elouen"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.14.2,<3.15"
assimulo = ">=3.7.2,<4"

[pypi-dependencies]
mxlpy = ">=0.30.0, <0.31"
mxlbricks = {path = ".", editable = true}
ipykernel = ">=7.1.0, <8"
